var Helpers = {};
var PlayerManager = {};
var Resources = {};
var ContextMenu = {};
var Map = {'Chunk':{}};
var Server = {};
var DbManager = {};
var Client = {};
var Social = {'Friends':{},'Chat':{},'Channel':{}};
var Game = {};
var Building = {};
var City = {};
var Player = {};
var CityManager = {};
var BuildingManager = {};

document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/BuildingManager/BuildingManagerBase.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/ContextMenu/ContextLabel.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/ContextMenu/ContextMenuBase.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/BuildingManager/BuildingManagerServer.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Helpers/Queue.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Building/BuildingBase.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/ContextMenu/ContextMenuBuilding.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Map/Chunk/ChunkBase.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Building/BuildingClient.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Map/Chunk/ChunkClient.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Player/PlayerBase.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Resources/ResourcesBase.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/ContextMenu/ContextMenuStage.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/City/CityBase.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/BuildingManager/BuildingManagerClient.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Resources/ResourcesServer.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/CityManager/CityManagerBase.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/City/CityClient.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/CityManager/CityManagerClient.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/PlayerManager/PlayerManagerClient.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Game/GameBase.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Player/PlayerClient.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Game/GameClient.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Client/Client.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Map/LevelGenerator.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Log.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Map/MapBase.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Map/Generator.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Social/Chat/ChatBase.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Map/MapServer.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/PlayerManager/PlayerManagerBase.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/DbManager/DbManager.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Singleton.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Social/Chat/ChatServer.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Player/PlayerServer.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/PlayerManager/PlayerManagerServer.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Game/GameServer.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Server/Server.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Node.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Helpers/Helper.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Browser.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Main.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Resources/ResourcesClient.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Map/MapClient.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Map/Chunk/ChunkServer.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Social/Channel/ChannelBase.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Social/Channel/ChannelClient.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Social/Channel/ChannelServer.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/Building/BuildingServer.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/City/CityServer.js"></scr'+'ipt>')
document.write('<scri'+'pt src="/js/TowerAdventure/release/toaster/CityManager/CityManagerServer.js"></scr'+'ipt>')